// <auto-generated />
using System;
using System.Collections.Generic;
using AutoGrader.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AutoGrader.Migrations
{
    [DbContext(typeof(AutoGraderDbContext))]
    partial class AutoGraderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AutoGrader.Models.Assignment.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<List<string>>("Languages");

                    b.Property<int>("MemoryLimit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("TimeLimit");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AutoGrader.Models.Assignment.AssignmentIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AssignmentId");

                    b.Property<List<string>>("Feedbacks");

                    b.Property<List<string>>("InputFileNames");

                    b.Property<List<string>>("OutputFileNames");

                    b.HasKey("ID");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentIO");
                });

            modelBuilder.Entity("AutoGrader.Models.Assignment.AssignmentIO", b =>
                {
                    b.HasOne("AutoGrader.Models.Assignment.Assignment")
                        .WithMany("IO")
                        .HasForeignKey("AssignmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
